### ISSUE TITLE
General todo's questions for finishing live coms paper

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpaceTutorials#17]
Posting already but will edit more to fill in details in abit. 

Text:

General readme:
- [ ] Make sure it contains all essential information including installation etc. It seems outdated right now. 

Change log:
- [ ] Do we want to maintain one big changelog or individual ones for each tutorial section?

Section checks:
- [ ] intro
- [ ] ...

Figures:
- [ ] Where are the figures being kept for the tutorial paper? Can the files that made figures be added somewhere to the repo? 

Tutorial checks:
- [ ] Tutorial 01: @lohedges 
     - [ ] Tested that all scripts run
     - [ ] uniformised feel of headers of all notebooks
     - [ ] clear instruction on how to execute the tutorial in terms of order etc. 
     - [ ] Checked spelling

- [ ] Tutorial 02: 
     - [ ] Tested that all scripts run
     - [ ] uniformised feel of headers of all notebooks
     - [ ] clear instruction on how to execute the tutorial in terms of order etc. 
     - [ ] Checked spelling

- [ ] Tutorial 03: @AdeleHardie 
     - [ ] Tested that all scripts run
     - [ ] uniformised feel of headers of all notebooks
     - [ ] clear instruction on how to execute the tutorial in terms of order etc. 
     - [ ] Checked spelling

- [ ] Tutorial 04: @ppxasjsm, @annamherz @fjclark 
     - [ ] Tested that all scripts run
     - [ ] uniformised feel of headers of all notebooks
     - [ ] clear instruction on how to execute the tutorial in terms of order etc. 
     - [ ] Checked spelling
